# -*- coding: utf-8 -*-
"""model_app

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Z1j5sArky9ucckUyMUqQaEiVYtRGYXLY
"""

!pip install streamlit

!pip install gdown
import gdown

# URL to the file on Google Drive
url = 'https://drive.google.com/uc?id=1_mjWC00hlyJYd-D3WF92nyCXB94ClQ5f'
output = 'food_classifier_model.keras'

# Download the model file
gdown.download(url, output, quiet=False)

!ls -lh

import streamlit as st
from tensorflow.keras.models import load_model
from tensorflow.keras.preprocessing import image
import numpy as np
from PIL import Image

# Load the trained model
model = load_model('food_classifier_model.keras')

# Define the class labels for food types
class_labels = [
    'burger', 'butter_naan', 'chai', 'chapati', 'chole_bhature', 'dal_makhani',
    'dhokla', 'fried_rice', 'idli', 'jalebi', 'kathi_roll', 'kadhai_paneer',
    'kulfi', 'masala_dosa', 'momos', 'paani_puri', 'pakode', 'pav_bhaji', 'pizza', 'samosa'
]

# Streamlit app title
st.title('Hi, I am Pratik\'s Food Classifier Model')

# Upload image
uploaded_image = st.file_uploader("Choose an image...", type=["jpg", "jpeg", "png"])

if uploaded_image is not None:
    # Open image and display it
    img = Image.open(uploaded_image)
    st.image(img, caption='Uploaded Image', use_column_width=True)

    # Prepare the image for model prediction
    img = img.resize((160, 160))  # Resize image to the model's input size
    img_array = np.array(img) / 255.0  # Normalize the image
    img_array = np.expand_dims(img_array, axis=0)  # Add batch dimension

    # Predict using the model
    predictions = model.predict(img_array)
    predicted_class = class_labels[np.argmax(predictions)]  # Get the class with the highest probability
    confidence = np.max(predictions) * 100  # Convert confidence to percentage

    # Display the result
    st.write(f"Hi, I am Pratik's food classifier model and I am {confidence:.2f}% sure that this is {predicted_class}.")